on: pull_request
jobs:
test:
  name: Testing iOS app
  runs-on: macOS-latest
  steps:
    - name: Checkout repository
    uses: actions/checkout@v1
    - name: Testing iOS app
    run: exec ./.github/scripts/test_app.sh